#!/usr/bin/env python3
"""Manage the single CoRHub version in apps/mobile/pubspec.yaml."""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION = r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)"
IDENTITY = "// Generated by tool/version.py; edit the version through that tool.\nconst String corHubAppName = 'CoRHub';\nconst String corHubAppVersion = '{version}';\nconst String corHubAppBuild = '{build}';\n"
TAG_PREFIX = "corhub-v"
LEGACY_TAG_PREFIX = "ts-phone-v"


def parse(value: str) -> tuple[tuple[int, ...], int]:
    match = re.fullmatch(VERSION + r"\+([1-9][0-9]*)", value)
    if not match:
        raise ValueError("version must be MAJOR.MINOR.PATCH+BUILD, without leading zeros")
    *parts, build = map(int, match.groups())
    # Flutter split APKs add 1000/2000/4000. Keep these ABI ranges disjoint.
    if build > 999:
        raise ValueError("build must be 1..999; migrate Android ABI version-code offsets before exceeding 999")
    return tuple(parts), build


def git(root: Path, *args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=root, text=True).strip()


def current(root: Path) -> str:
    values = re.findall(r"(?m)^version: ([^\s#]+)$", (root / "apps/mobile/pubspec.yaml").read_text())
    if len(values) != 1:
        raise ValueError("pubspec must have exactly one version field")
    parse(values[0])
    return values[0]


def identity(value: str) -> str:
    version, build = value.split("+")
    return IDENTITY.format(version=version, build=build)


def require_newer(value: str, previous: str) -> None:
    version, build = parse(value)
    old_version, old_build = parse(previous)
    if version < old_version or build <= old_build:
        raise ValueError(f"{value} must not decrease the semantic version and must increase the build above {previous}")


def release_tags(root: Path) -> list[tuple[str, str]]:
    """Keep the build-number history across the repository/brand rename."""
    tags = git(root, "tag", "--list", TAG_PREFIX + "*", LEGACY_TAG_PREFIX + "*").splitlines()
    return [
        (tag, tag.removeprefix(TAG_PREFIX) if tag.startswith(TAG_PREFIX) else tag.removeprefix(LEGACY_TAG_PREFIX))
        for tag in tags
    ]


def check(root: Path, *, tag: str | None = None, release: bool = False) -> str:
    value = current(root)
    if (root / "apps/mobile/lib/app_identity.dart").read_text() != identity(value):
        raise ValueError("Settings identity is stale; run python3 tool/version.py sync")
    expected = TAG_PREFIX + value
    if tag is not None and tag != expected:
        raise ValueError(f"tag must be {expected}, got {tag}")
    for previous_tag, previous_version in release_tags(root):
        if previous_tag == expected:
            continue
        # A working tree may still use the last version while preparing changes.
        # Publishing under the new prefix must never reuse a legacy build number.
        if not release and previous_version == value:
            continue
        require_newer(value, previous_version)
    if release:
        if tag is None:
            raise ValueError("release validation requires --tag")
        if git(root, "status", "--porcelain", "--untracked-files=normal"):
            raise ValueError("release requires a clean Git checkout")
        if git(root, "rev-parse", f"refs/tags/{tag}^{{commit}}") != git(root, "rev-parse", "HEAD"):
            raise ValueError("release tag must point to HEAD")
        notes(root, value)
    return value


def notes(root: Path, value: str) -> str:
    text = (root / "CHANGELOG.md").read_text()
    match = re.search(r"(?ms)^## " + re.escape(value) + r"\n(.*?)(?=^## |\Z)", text)
    if not match or not match[1].strip():
        raise ValueError(f"CHANGELOG.md needs a nonempty section: ## {value}")
    return match[1].strip() + "\n"


def set_version(root: Path, value: str) -> None:
    parse(value)
    require_newer(value, current(root))
    for _, previous_version in release_tags(root):
        require_newer(value, previous_version)
    pubspec = root / "apps/mobile/pubspec.yaml"
    pubspec.write_text(re.sub(r"(?m)^version: [^\n]+$", "version: " + value, pubspec.read_text()))
    (root / "apps/mobile/lib/app_identity.dart").write_text(identity(value))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    validate = commands.add_parser("check")
    validate.add_argument("--tag")
    validate.add_argument("--release", action="store_true")
    update = commands.add_parser("set")
    update.add_argument("version", help="MAJOR.MINOR.PATCH+BUILD; build always increases")
    commands.add_parser("sync")
    commands.add_parser("tag")
    commands.add_parser("notes")
    args = parser.parse_args()
    try:
        if args.command == "set":
            set_version(ROOT, args.version)
        elif args.command == "sync":
            (ROOT / "apps/mobile/lib/app_identity.dart").write_text(identity(current(ROOT)))
        elif args.command == "check":
            print(check(ROOT, tag=args.tag, release=args.release))
        elif args.command == "tag":
            print(TAG_PREFIX + current(ROOT))
        else:
            print(notes(ROOT, current(ROOT)), end="")
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"Version check failed: {error}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
